title: Dalmura
email: contact@dalmura.com.au
description: >
  Dalmura is a family run website by the Robbins family covering our Genealogy and some personal sites/projects.
  It is named after Dalmura Avenue in Merbein, Victoria, Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dalmura.com.au" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: michael-robbins

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - README.md
